# Generated by Django 5.1.4 on 2025-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_tutor',
            field=models.BooleanField(default=False, verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='introduction',
            field=models.TextField(blank=True, verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subject_teaching',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subject Teaching'),
        ),
    ]
